### ISSUE TITLE
Introduce faster streams for REST and Document client setup 

### ISSUE THREAD

**Issue by uweschaefer** [uweschaefer/factcast#23]
Document REST setup
https://docs.factcast.org/setup/client/rest/

**Comment by JoergAdler** [comment]
First experiments with the multi http structure weren't very promising. So I introduced a second stream for the full facts. 

This stream could cause very high loads on the server, due it could not be cached.

**Comment by uweschaefer** [comment]
I would not be afraid of the load immediate Event transfer introduces. With GRPC, we see that almost alle Events need to be cached client side (infinispan for instance) in order to be faster with a "idOnly" stream, as the fetching of single Events creates most of the perfomance hit.

**Comment by JoergAdler** [comment]
I would say it strongly depends on the usage and infrastructure. Of course there is absolutely no point in using the Id-Stream, if one does not have a http-cache in front of the REST-API.

But if one has many subscribers, each only interested in few (big) facts, one can consider using the id stream. Getting the benefits of HTTP-Caching on the server side. 

So I would leave both options in the API.

**Comment by uweschaefer** [comment]
Sure. Choice is good – same with the GRPC API.
