### ISSUE TITLE
Rest: support for postQueryFiltering is missing?

### ISSUE THREAD

**Issue by uweschaefer** [uweschaefer/factcast#36]
FactSpecParam sould probably have jsFilterScript.

**Comment by JoergAdler** [comment]
As you can see here: https://docs.factcast.org/usage/rest/api-guide/#_fields there is already the field factspec[].jsFilterScript.

**Comment by uweschaefer** [comment]
While i appreciate it being documented, wouldn't it be nice, if it was implemented as well? :)

**Comment by JoergAdler** [comment]
It is implemented :-) I just forgot to delete the class FactSpecParam (it isn't used anywhere). As you can see here, Subscriptions hava a list of FactSpecs as fields https://github.com/uweschaefer/factcast/blob/master/factcast-server-rest/src/main/java/org/factcast/server/rest/resources/SubscriptionRequestParams.java

**Comment by uweschaefer** [comment]
ahh :)
